import { ClientContract } from '../types';
import { generateDeltaForceScreenshot } from '../utils/imageUtils';

export const AVAILABLE_CLIENT_CONTRACTS: ClientContract[] = [
  {
    id: 'contract-1',
    post_number: 1,
    client_name: 'GhostSniper_99',
    account_tag: 'VIP-HAWK-7741',
    game_mode: 'Hazard Operations // Extraction',
    current_rank: 'Master II',
    target_rank: 'Pinnacle Grandmaster',
    initial_score: 14200000,
    target_score: 25000000,
    recommended_shift: 'day',
    estimated_reward_ar: 10800,
    priority: 'Urgente',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-2',
    post_number: 2,
    client_name: 'ViperPrime_FR',
    account_tag: 'FR-ZONE-4411',
    game_mode: 'Havoc Warfare // Breach',
    current_rank: 'High Sovereign (Rank 50)',
    target_rank: 'Apex Legend Top 100',
    initial_score: 22000000,
    target_score: 30000000,
    recommended_shift: 'night',
    estimated_reward_ar: 8000,
    priority: 'Haute',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-3',
    post_number: 3,
    client_name: 'AlphaDelta_EU',
    account_tag: 'EU-COMM-9912',
    game_mode: 'Hazard Operations // Extraction',
    current_rank: 'Diamond III',
    target_rank: 'Master I',
    initial_score: 12000000,
    target_score: 20000000,
    recommended_shift: 'day',
    estimated_reward_ar: 8000,
    priority: 'Normale',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-4',
    post_number: 4,
    client_name: 'ShadowRaptor_9',
    account_tag: 'DE-OPS-5521',
    game_mode: 'Hazard Operations // Mandelbrick Recovery',
    current_rank: 'Platinum I',
    target_rank: 'Diamond II',
    initial_score: 8500000,
    target_score: 18000000,
    recommended_shift: 'night',
    estimated_reward_ar: 9500,
    priority: 'Haute',
    region_server: 'EU-Central (22ms)',
  },
  {
    id: 'contract-5',
    post_number: 5,
    client_name: 'TitanStrike_US',
    account_tag: 'US-HAWK-3301',
    game_mode: 'Havoc Warfare // CQB Domination',
    current_rank: 'Diamond II',
    target_rank: 'High Sovereign',
    initial_score: 15000000,
    target_score: 28000000,
    recommended_shift: 'night',
    estimated_reward_ar: 13000,
    priority: 'Urgente',
    region_server: 'US-East (Virginia)',
  },
  {
    id: 'contract-6',
    post_number: 6,
    client_name: 'KiloBravo_Ops',
    account_tag: 'FR-TAC-8899',
    game_mode: 'Hazard Operations // Level Push',
    current_rank: 'Gold III',
    target_rank: 'Platinum I',
    initial_score: 5000000,
    target_score: 15000000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Normale',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-7',
    post_number: 7,
    client_name: 'CyberSpectre_07',
    account_tag: 'SPECTRE-07X',
    game_mode: 'Tactical Extraction // Zero Dam',
    current_rank: 'Master I',
    target_rank: 'Pinnacle Elite',
    initial_score: 16500000,
    target_score: 26500000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Haute',
    region_server: 'EU-West (London)',
  },
  {
    id: 'contract-8',
    post_number: 8,
    client_name: 'BlackMamba_Snipe',
    account_tag: 'MAMBA-99A',
    game_mode: 'Havoc Warfare // Layali Grove',
    current_rank: 'Diamond I',
    target_rank: 'Master II',
    initial_score: 19000000,
    target_score: 27000000,
    recommended_shift: 'night',
    estimated_reward_ar: 8000,
    priority: 'Normale',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-9',
    post_number: 9,
    client_name: 'Phoenix_Ghost',
    account_tag: 'PHX-TAC-2210',
    game_mode: 'Hazard Operations // Mandelbrick',
    current_rank: 'Platinum II',
    target_rank: 'Diamond I',
    initial_score: 11000000,
    target_score: 21000000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Urgente',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-10',
    post_number: 10,
    client_name: 'ApexPredator_DF',
    account_tag: 'PRED-DF-55',
    game_mode: 'Tactical Extraction // Space City',
    current_rank: 'Master III',
    target_rank: 'Grandmaster Top 50',
    initial_score: 24000000,
    target_score: 36000000,
    recommended_shift: 'night',
    estimated_reward_ar: 12000,
    priority: 'Urgente',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-11',
    post_number: 11,
    client_name: 'ValkyrieOps_FR',
    account_tag: 'VALK-FR-77',
    game_mode: 'Havoc Warfare // Ascension',
    current_rank: 'Gold I',
    target_rank: 'Diamond III',
    initial_score: 7000000,
    target_score: 17000000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Normale',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-12',
    post_number: 12,
    client_name: 'DesertEagle_Pro',
    account_tag: 'DEAGLE-PRO-9',
    game_mode: 'Hazard Operations // Secure Loot',
    current_rank: 'Diamond III',
    target_rank: 'Master I',
    initial_score: 13500000,
    target_score: 23500000,
    recommended_shift: 'night',
    estimated_reward_ar: 10000,
    priority: 'Haute',
    region_server: 'EU-Central (Munich)',
  },
  {
    id: 'contract-13',
    post_number: 13,
    client_name: 'ShadowRider_Mada',
    account_tag: 'MG-TAN-8801',
    game_mode: 'Havoc Warfare // Trench Assault',
    current_rank: 'Master I',
    target_rank: 'Pinnacle Sovereign',
    initial_score: 18000000,
    target_score: 30000000,
    recommended_shift: 'night',
    estimated_reward_ar: 12000,
    priority: 'Urgente',
    region_server: 'South Africa (Johannesburg)',
  },
  {
    id: 'contract-14',
    post_number: 14,
    client_name: 'PhantomOperator',
    account_tag: 'PHANTOM-88',
    game_mode: 'Tactical Extraction // Threshold',
    current_rank: 'Platinum III',
    target_rank: 'Diamond II',
    initial_score: 9500000,
    target_score: 19500000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Normale',
    region_server: 'EU-West (London)',
  },
  {
    id: 'contract-15',
    post_number: 15,
    client_name: 'ZeroTolerance_X',
    account_tag: 'ZERO-TOL-42',
    game_mode: 'Hazard Operations // Secret Armory',
    current_rank: 'Diamond II',
    target_rank: 'Master II',
    initial_score: 15500000,
    target_score: 25500000,
    recommended_shift: 'night',
    estimated_reward_ar: 10000,
    priority: 'Haute',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-16',
    post_number: 16,
    client_name: 'ThunderBolt_99',
    account_tag: 'TBOLT-99-AF',
    game_mode: 'Havoc Warfare // Heavy Armor',
    current_rank: 'Gold II',
    target_rank: 'Platinum I',
    initial_score: 6200000,
    target_score: 15200000,
    recommended_shift: 'day',
    estimated_reward_ar: 9000,
    priority: 'Normale',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-17',
    post_number: 17,
    client_name: 'NightStalker_DF',
    account_tag: 'NSTALK-DF-03',
    game_mode: 'Tactical Extraction // Midnight Raid',
    current_rank: 'Master II',
    target_rank: 'Grandmaster Pinnacle',
    initial_score: 21500000,
    target_score: 33500000,
    recommended_shift: 'night',
    estimated_reward_ar: 12000,
    priority: 'Urgente',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-18',
    post_number: 18,
    client_name: 'Overlord_HQ',
    account_tag: 'OVERLORD-HQ-1',
    game_mode: 'Hazard Operations // High Value Bunker',
    current_rank: 'Diamond I',
    target_rank: 'Master III',
    initial_score: 17800000,
    target_score: 27800000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Haute',
    region_server: 'EU-West (London)',
  },
  {
    id: 'contract-19',
    post_number: 19,
    client_name: 'RedDragon_Tactical',
    account_tag: 'REDDRAGON-8',
    game_mode: 'Havoc Warfare // Urban Incursion',
    current_rank: 'Platinum I',
    target_rank: 'Diamond III',
    initial_score: 10200000,
    target_score: 19200000,
    recommended_shift: 'day',
    estimated_reward_ar: 9000,
    priority: 'Normale',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-20',
    post_number: 20,
    client_name: 'QuantumStrike_X',
    account_tag: 'QUANTUM-20X',
    game_mode: 'Hazard Operations // Classified Site',
    current_rank: 'Master III',
    target_rank: 'Pinnacle Sovereign #01',
    initial_score: 26000000,
    target_score: 40000000,
    recommended_shift: 'night',
    estimated_reward_ar: 14000,
    priority: 'Urgente',
    region_server: 'EU-West (Paris)',
  }
];

