import { User, PostSession, SecurityViolation, SalaryAdvanceRequest, ChatMessage, ClientContract } from '../types';
import { generateDeltaForceScreenshot } from '../utils/imageUtils';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin-1',
    username: 'admin',
    name: 'Commandant Eric',
    role: 'admin',
    status: 'active',
    shift: 'day',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    phone: '+261 34 11 222 33',
    cv_url: 'cv-commandant-eric.pdf',
    performance_badge: 'Elite',
    total_score_boosted: 0,
    total_earnings_ar: 0,
    pending_advance_ar: 0,
  },
  {
    id: 'user-emp-1',
    username: 'tojo',
    name: 'Tojo Sniper',
    role: 'employee',
    status: 'active',
    shift: 'day',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80',
    phone: '+261 32 45 678 90',
    cv_url: 'cv_tojo_sniper.pdf',
    cv_data: {
      rank: 'Apex Pinnacle (Grandmaster)',
      gameExperience: '4 Years FPS & Tactical Extraction (Delta Force Hawk Ops, Tarkov)',
      kdRatio: '4.85 K/D',
      hardware: 'RTX 4080 / i9-13900K / 240Hz OLED / Fiber 100Mbps low-ping',
      joinedDate: '2026-01-15',
      languages: ['Malagasy', 'French', 'English'],
      specialty: 'Long-range reconnaissance & Mandelbrick rapid extraction'
    },
    performance_badge: 'Top Booster',
    total_score_boosted: 52000000,
    total_earnings_ar: 52000,
    pending_advance_ar: 15000,
  },
  {
    id: 'user-emp-2',
    username: 'rado',
    name: 'Rado Assault',
    role: 'employee',
    status: 'active',
    shift: 'night',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    phone: '+261 33 89 123 45',
    cv_url: 'cv_rado_assault.pdf',
    cv_data: {
      rank: 'High Sovereign (Master I)',
      gameExperience: '3 Years competitive Havoc Warfare & Tactical Infiltration',
      kdRatio: '3.92 K/D',
      hardware: 'RTX 3070 Ti / Ryzen 7 7800X3D / 165Hz Monitor',
      joinedDate: '2026-03-01',
      languages: ['Malagasy', 'French'],
      specialty: 'Close-quarters breach, squad wipe & fast level-ups'
    },
    performance_badge: 'Elite',
    total_score_boosted: 38000000,
    total_earnings_ar: 38000,
    pending_advance_ar: 0,
  },
  {
    id: 'user-emp-3',
    username: 'mialy',
    name: 'Mialy Support',
    role: 'employee',
    status: 'active',
    shift: 'day',
    is_online: false,
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    phone: '+261 34 56 789 01',
    cv_url: 'cv_mialy_support.pdf',
    cv_data: {
      rank: 'Veteran Tactical (Diamond II)',
      gameExperience: '2 Years Delta Force Operator / Medic specialist',
      kdRatio: '3.10 K/D',
      hardware: 'RTX 4060 / i7-12700K / 144Hz IPS',
      joinedDate: '2026-05-10',
      languages: ['Malagasy', 'French', 'English'],
      specialty: 'Hazard zone resource farming & safe escort extraction'
    },
    performance_badge: 'Standard',
    total_score_boosted: 24000000,
    total_earnings_ar: 24000,
    pending_advance_ar: 0,
  },
  {
    id: 'user-emp-blocked',
    username: 'cheater99',
    name: 'Herilala Blocked',
    role: 'employee',
    status: 'blocked',
    shift: 'night',
    is_online: false,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    phone: '+261 32 99 999 99',
    cv_url: 'cv_herilala.pdf',
    cv_data: {
      rank: 'Unranked (Suspended)',
      gameExperience: 'Flagged for multiple score falsifications',
      kdRatio: '1.20 K/D',
      hardware: 'Unknown',
      joinedDate: '2026-06-01',
      languages: ['Malagasy'],
      specialty: 'Terminated due to score inversion tamper'
    },
    performance_badge: 'Under Watch',
    total_score_boosted: 4000000,
    total_earnings_ar: 4000,
    pending_advance_ar: 0,
  }
];

export const INITIAL_POSTS: PostSession[] = [
  {
    id: 'post-active-1',
    employee_id: 'user-emp-1',
    employee_name: 'Tojo Sniper',
    client_name: 'GhostSniper_99',
    account_tag: 'VIP-HAWK-7741',
    target_score: 25000000,
    initial_score: 14200000,
    current_score: 18500000,
    remaining_score: 6500000,
    status: 'active',
    shift_type: 'day',
    date: '2026-09-29',
    start_time: '08:15:00',
    start_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Tojo Sniper',
      score: 14200000,
      clientTag: 'GhostSniper_99 #7741',
      isVictory: true,
      timestamp: '2026-09-29 08:15:00'
    }),
    created_at: '2026-09-29T08:15:00.000Z',
    updated_at: '2026-09-29T10:20:00.000Z',
  },
  {
    id: 'post-pending-end-1',
    employee_id: 'user-emp-3',
    employee_name: 'Mialy Support',
    client_name: 'AlphaDelta_EU',
    account_tag: 'EU-COMM-9912',
    target_score: 20000000,
    initial_score: 12000000,
    current_score: 20500000,
    final_score: 20500000,
    remaining_score: 0,
    status: 'pending_end',
    shift_type: 'day',
    date: '2026-09-29',
    start_time: '08:30:00',
    end_time: '17:45:00',
    start_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Mialy Support',
      score: 12000000,
      clientTag: 'AlphaDelta_EU #9912',
      isVictory: true,
      timestamp: '2026-09-29 08:30:00'
    }),
    end_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Mialy Support',
      score: 20500000,
      clientTag: 'AlphaDelta_EU #9912',
      isVictory: true,
      timestamp: '2026-09-29 17:45:00'
    }),
    notes: 'Extraction completed with 4 mandelbricks. Target exceeded by +500,000 pts.',
    created_at: '2026-09-29T08:30:00.000Z',
    updated_at: '2026-09-29T17:45:00.000Z',
  },
  {
    id: 'post-pending-start-1',
    employee_id: 'user-emp-2',
    employee_name: 'Rado Assault',
    client_name: 'ViperPrime_FR',
    account_tag: 'FR-ZONE-4411',
    target_score: 30000000,
    initial_score: 22000000,
    current_score: 22000000,
    remaining_score: 8000000,
    status: 'pending_start',
    shift_type: 'night',
    date: '2026-09-29',
    start_time: '20:05:00',
    start_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Rado Assault',
      score: 22000000,
      clientTag: 'ViperPrime_FR #4411',
      isVictory: true,
      timestamp: '2026-09-29 20:05:00'
    }),
    created_at: '2026-09-29T20:05:00.000Z',
    updated_at: '2026-09-29T20:05:00.000Z',
  },
  // Completed shifts for calendar history
  {
    id: 'post-hist-1',
    employee_id: 'user-emp-1',
    employee_name: 'Tojo Sniper',
    client_name: 'Vanguard_Striker',
    account_tag: 'US-HAWK-3301',
    target_score: 18000000,
    initial_score: 10000000,
    current_score: 18200000,
    final_score: 18200000,
    remaining_score: 0,
    status: 'completed',
    shift_type: 'day',
    date: '2026-09-28',
    start_time: '08:00:00',
    end_time: '17:30:00',
    start_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Tojo Sniper',
      score: 10000000,
      clientTag: 'Vanguard_Striker',
      timestamp: '2026-09-28 08:00:00'
    }),
    end_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Tojo Sniper',
      score: 18200000,
      clientTag: 'Vanguard_Striker',
      timestamp: '2026-09-28 17:30:00'
    }),
    calculated_ar: 8200,
    created_at: '2026-09-28T08:00:00.000Z',
    updated_at: '2026-09-28T17:35:00.000Z',
  },
  {
    id: 'post-hist-2',
    employee_id: 'user-emp-2',
    employee_name: 'Rado Assault',
    client_name: 'ShadowOps_GER',
    account_tag: 'DE-OPS-6621',
    target_score: 15000000,
    initial_score: 7500000,
    current_score: 15000000,
    final_score: 15000000,
    remaining_score: 0,
    status: 'completed',
    shift_type: 'night',
    date: '2026-09-27',
    start_time: '20:10:00',
    end_time: '05:40:00',
    start_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Rado Assault',
      score: 7500000,
      clientTag: 'ShadowOps_GER',
      timestamp: '2026-09-27 20:10:00'
    }),
    end_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Rado Assault',
      score: 15000000,
      clientTag: 'ShadowOps_GER',
      timestamp: '2026-09-28 05:40:00'
    }),
    calculated_ar: 7500,
    created_at: '2026-09-27T20:10:00.000Z',
    updated_at: '2026-09-28T05:45:00.000Z',
  },
  {
    id: 'post-hist-3',
    employee_id: 'user-emp-1',
    employee_name: 'Tojo Sniper',
    client_name: 'Kilo_Bravo_9',
    account_tag: 'FR-TAC-8899',
    target_score: 12000000,
    initial_score: 5000000,
    current_score: 12100000,
    final_score: 12100000,
    remaining_score: 0,
    status: 'completed',
    shift_type: 'day',
    date: '2026-09-25',
    start_time: '08:30:00',
    end_time: '18:00:00',
    start_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Tojo Sniper',
      score: 5000000,
      clientTag: 'Kilo_Bravo_9',
      timestamp: '2026-09-25 08:30:00'
    }),
    end_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Tojo Sniper',
      score: 12100000,
      clientTag: 'Kilo_Bravo_9',
      timestamp: '2026-09-25 18:00:00'
    }),
    calculated_ar: 7100,
    created_at: '2026-09-25T08:30:00.000Z',
    updated_at: '2026-09-25T18:05:00.000Z',
  },
  {
    id: 'post-hist-4',
    employee_id: 'user-emp-3',
    employee_name: 'Mialy Support',
    client_name: 'TestRun_Calibration',
    account_tag: 'DF-QA-0001',
    target_score: 5000000,
    initial_score: 2000000,
    current_score: 5000000,
    final_score: 5000000,
    remaining_score: 0,
    status: 'completed',
    shift_type: 'day',
    date: '2026-09-20',
    start_time: '09:00:00',
    end_time: '14:00:00',
    start_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Mialy Support',
      score: 2000000,
      clientTag: 'TestRun_Calibration',
      timestamp: '2026-09-20 09:00:00'
    }),
    end_proof_url: generateDeltaForceScreenshot({
      operatorName: 'Mialy Support',
      score: 5000000,
      clientTag: 'TestRun_Calibration',
      timestamp: '2026-09-20 14:00:00'
    }),
    calculated_ar: 3000,
    created_at: '2026-09-20T09:00:00.000Z',
    updated_at: '2026-09-20T14:05:00.000Z',
  }
];

export const INITIAL_SECURITY_LOGS: SecurityViolation[] = [
  {
    id: 'sec-viol-1',
    employee_id: 'user-emp-blocked',
    employee_name: 'Herilala Blocked',
    violation_type: 'score_inversion',
    description: 'Score Inversion Tamper: Final score entered (11,000,000) was lower than Initial verified score (14,500,000).',
    timestamp: '2026-09-28 22:41:19',
    details: {
      initial_score: 14500000,
      attempted_score: 11000000,
      client_name: 'GhostSniper_99',
    },
    resolved: false
  },
  {
    id: 'sec-viol-2',
    employee_id: 'user-emp-blocked',
    employee_name: 'Herilala Blocked',
    violation_type: 'multi_post_attempt',
    description: 'Anti-Multi-Poste Block: Attempted to launch second concurrent shift while session "post-viol-01" was active.',
    timestamp: '2026-09-28 22:45:02',
    details: {
      client_name: 'ApexRaptor',
      active_post_id: 'post-viol-01'
    },
    resolved: false
  }
];

export const INITIAL_ADVANCE_REQUESTS: SalaryAdvanceRequest[] = [
  {
    id: 'adv-1',
    employee_id: 'user-emp-1',
    employee_name: 'Tojo Sniper',
    amount_ar: 15000,
    reason: 'Frais de connexion fibre optique de secours et réparation onduleur pour session nocturne',
    request_date: '2026-09-28',
    status: 'pending',
  },
  {
    id: 'adv-2',
    employee_id: 'user-emp-2',
    employee_name: 'Rado Assault',
    amount_ar: 20000,
    reason: 'Remplacement alimentation PC de jeu (Delta Force crash reboot)',
    request_date: '2026-09-24',
    status: 'approved',
    admin_notes: 'Approuvé par Commandant Eric - Déduit sur la paie du 30/09'
  }
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender_id: 'user-admin-1',
    sender_name: 'Commandant Eric',
    sender_role: 'admin',
    recipient_id: 'all',
    message: 'Attention tous les boosters : vérifiez bien vos captures d\'écran de départ et de fin. Le système anti-triche vérifie la cohérence des scores et watermarks.',
    timestamp: '2026-09-29 07:45:00'
  },
  {
    id: 'msg-2',
    sender_id: 'user-emp-1',
    sender_name: 'Tojo Sniper',
    sender_role: 'employee',
    recipient_id: 'user-admin-1',
    message: 'Reçu Commandant, j\'ai commencé sur GhostSniper_99, déjà +4.3M de score ce matin.',
    timestamp: '2026-09-29 09:30:12'
  },
  {
    id: 'msg-3',
    sender_id: 'user-admin-1',
    sender_name: 'Commandant Eric',
    sender_role: 'admin',
    recipient_id: 'user-emp-1',
    message: 'Super travail Tojo. Continue sur ce rythme pour atteindre l\'objectif de 25M.',
    timestamp: '2026-09-29 09:34:00'
  }
];

export const AVAILABLE_CLIENT_CONTRACTS: ClientContract[] = [
  {
    id: 'contract-1',
    post_number: 1,
    client_name: 'GhostSniper_99',
    account_tag: 'VIP-HAWK-7741',
    game_mode: 'Hazard Operations // Extraction',
    current_rank: 'Master II',
    target_rank: 'Pinnacle Grandmaster',
    initial_score: 14200000,
    target_score: 25000000,
    recommended_shift: 'day',
    estimated_reward_ar: 10800,
    priority: 'Urgente',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-2',
    post_number: 2,
    client_name: 'ViperPrime_FR',
    account_tag: 'FR-ZONE-4411',
    game_mode: 'Havoc Warfare // Breach',
    current_rank: 'High Sovereign (Rank 50)',
    target_rank: 'Apex Legend Top 100',
    initial_score: 22000000,
    target_score: 30000000,
    recommended_shift: 'night',
    estimated_reward_ar: 8000,
    priority: 'Haute',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-3',
    post_number: 3,
    client_name: 'AlphaDelta_EU',
    account_tag: 'EU-COMM-9912',
    game_mode: 'Hazard Operations // Extraction',
    current_rank: 'Diamond III',
    target_rank: 'Master I',
    initial_score: 12000000,
    target_score: 20000000,
    recommended_shift: 'day',
    estimated_reward_ar: 8000,
    priority: 'Normale',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-4',
    post_number: 4,
    client_name: 'ShadowRaptor_9',
    account_tag: 'DE-OPS-5521',
    game_mode: 'Hazard Operations // Mandelbrick Recovery',
    current_rank: 'Platinum I',
    target_rank: 'Diamond II',
    initial_score: 8500000,
    target_score: 18000000,
    recommended_shift: 'night',
    estimated_reward_ar: 9500,
    priority: 'Haute',
    region_server: 'EU-Central (22ms)',
  },
  {
    id: 'contract-5',
    post_number: 5,
    client_name: 'TitanStrike_US',
    account_tag: 'US-HAWK-3301',
    game_mode: 'Havoc Warfare // CQB Domination',
    current_rank: 'Diamond II',
    target_rank: 'High Sovereign',
    initial_score: 15000000,
    target_score: 28000000,
    recommended_shift: 'night',
    estimated_reward_ar: 13000,
    priority: 'Urgente',
    region_server: 'US-East (Virginia)',
  },
  {
    id: 'contract-6',
    post_number: 6,
    client_name: 'KiloBravo_Ops',
    account_tag: 'FR-TAC-8899',
    game_mode: 'Hazard Operations // Level Push',
    current_rank: 'Gold III',
    target_rank: 'Platinum I',
    initial_score: 5000000,
    target_score: 15000000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Normale',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-7',
    post_number: 7,
    client_name: 'CyberSpectre_07',
    account_tag: 'SPECTRE-07X',
    game_mode: 'Tactical Extraction // Zero Dam',
    current_rank: 'Master I',
    target_rank: 'Pinnacle Elite',
    initial_score: 16500000,
    target_score: 26500000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Haute',
    region_server: 'EU-West (London)',
  },
  {
    id: 'contract-8',
    post_number: 8,
    client_name: 'BlackMamba_Snipe',
    account_tag: 'MAMBA-99A',
    game_mode: 'Havoc Warfare // Layali Grove',
    current_rank: 'Diamond I',
    target_rank: 'Master II',
    initial_score: 19000000,
    target_score: 27000000,
    recommended_shift: 'night',
    estimated_reward_ar: 8000,
    priority: 'Normale',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-9',
    post_number: 9,
    client_name: 'Phoenix_Ghost',
    account_tag: 'PHX-TAC-2210',
    game_mode: 'Hazard Operations // Mandelbrick',
    current_rank: 'Platinum II',
    target_rank: 'Diamond I',
    initial_score: 11000000,
    target_score: 21000000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Urgente',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-10',
    post_number: 10,
    client_name: 'ApexPredator_DF',
    account_tag: 'PRED-DF-55',
    game_mode: 'Tactical Extraction // Space City',
    current_rank: 'Master III',
    target_rank: 'Grandmaster Top 50',
    initial_score: 24000000,
    target_score: 36000000,
    recommended_shift: 'night',
    estimated_reward_ar: 12000,
    priority: 'Urgente',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-11',
    post_number: 11,
    client_name: 'ValkyrieOps_FR',
    account_tag: 'VALK-FR-77',
    game_mode: 'Havoc Warfare // Ascension',
    current_rank: 'Gold I',
    target_rank: 'Diamond III',
    initial_score: 7000000,
    target_score: 17000000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Normale',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-12',
    post_number: 12,
    client_name: 'DesertEagle_Pro',
    account_tag: 'DEAGLE-PRO-9',
    game_mode: 'Hazard Operations // Secure Loot',
    current_rank: 'Diamond III',
    target_rank: 'Master I',
    initial_score: 13500000,
    target_score: 23500000,
    recommended_shift: 'night',
    estimated_reward_ar: 10000,
    priority: 'Haute',
    region_server: 'EU-Central (Munich)',
  },
  {
    id: 'contract-13',
    post_number: 13,
    client_name: 'ShadowRider_Mada',
    account_tag: 'MG-TAN-8801',
    game_mode: 'Havoc Warfare // Trench Assault',
    current_rank: 'Master I',
    target_rank: 'Pinnacle Sovereign',
    initial_score: 18000000,
    target_score: 30000000,
    recommended_shift: 'night',
    estimated_reward_ar: 12000,
    priority: 'Urgente',
    region_server: 'South Africa (Johannesburg)',
  },
  {
    id: 'contract-14',
    post_number: 14,
    client_name: 'PhantomOperator',
    account_tag: 'PHANTOM-88',
    game_mode: 'Tactical Extraction // Threshold',
    current_rank: 'Platinum III',
    target_rank: 'Diamond II',
    initial_score: 9500000,
    target_score: 19500000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Normale',
    region_server: 'EU-West (London)',
  },
  {
    id: 'contract-15',
    post_number: 15,
    client_name: 'ZeroTolerance_X',
    account_tag: 'ZERO-TOL-42',
    game_mode: 'Hazard Operations // Secret Armory',
    current_rank: 'Diamond II',
    target_rank: 'Master II',
    initial_score: 15500000,
    target_score: 25500000,
    recommended_shift: 'night',
    estimated_reward_ar: 10000,
    priority: 'Haute',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-16',
    post_number: 16,
    client_name: 'ThunderBolt_99',
    account_tag: 'TBOLT-99-AF',
    game_mode: 'Havoc Warfare // Heavy Armor',
    current_rank: 'Gold II',
    target_rank: 'Platinum I',
    initial_score: 6200000,
    target_score: 15200000,
    recommended_shift: 'day',
    estimated_reward_ar: 9000,
    priority: 'Normale',
    region_server: 'EU-West (Paris)',
  },
  {
    id: 'contract-17',
    post_number: 17,
    client_name: 'NightStalker_DF',
    account_tag: 'NSTALK-DF-03',
    game_mode: 'Tactical Extraction // Midnight Raid',
    current_rank: 'Master II',
    target_rank: 'Grandmaster Pinnacle',
    initial_score: 21500000,
    target_score: 33500000,
    recommended_shift: 'night',
    estimated_reward_ar: 12000,
    priority: 'Urgente',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-18',
    post_number: 18,
    client_name: 'Overlord_HQ',
    account_tag: 'OVERLORD-HQ-1',
    game_mode: 'Hazard Operations // High Value Bunker',
    current_rank: 'Diamond I',
    target_rank: 'Master III',
    initial_score: 17800000,
    target_score: 27800000,
    recommended_shift: 'day',
    estimated_reward_ar: 10000,
    priority: 'Haute',
    region_server: 'EU-West (London)',
  },
  {
    id: 'contract-19',
    post_number: 19,
    client_name: 'RedDragon_Tactical',
    account_tag: 'REDDRAGON-8',
    game_mode: 'Havoc Warfare // Urban Incursion',
    current_rank: 'Platinum I',
    target_rank: 'Diamond III',
    initial_score: 10200000,
    target_score: 19200000,
    recommended_shift: 'day',
    estimated_reward_ar: 9000,
    priority: 'Normale',
    region_server: 'EU-Central (Frankfurt)',
  },
  {
    id: 'contract-20',
    post_number: 20,
    client_name: 'QuantumStrike_X',
    account_tag: 'QUANTUM-20X',
    game_mode: 'Hazard Operations // Classified Site',
    current_rank: 'Master III',
    target_rank: 'Pinnacle Sovereign #01',
    initial_score: 26000000,
    target_score: 40000000,
    recommended_shift: 'night',
    estimated_reward_ar: 14000,
    priority: 'Urgente',
    region_server: 'EU-West (Paris)',
  }
];

